import { getSession } from 'next-auth/react';
import Head from 'next/head';
import Feed from '../components/feedpage/Feed';
import Header from '../components/header/Header';
import Login from '../components/Login';
import RightSidebar from '../components/rightsidebar/RightSidebar';
import Sidebar from '../components/sidebar/Sidebar';

export default function Home({ session }) {
  if (!session) return <Login />;
  return (
    <div>
      <Head>
        <title>Facebook clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* For the header */}
      <Header />
      <main className=" flex bg-gray-100">
        {/* For the left sidebar */}
        <Sidebar />
        {/* feedPage for post and everything */}
        <Feed />
        {/* right sidebar */}
        <RightSidebar />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: { session },
  };
}
